### ISSUE TITLE
Bad use of broadcast can bring down a suite.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1415]
E.g. in a date-time cycling suite:
```
% cylc broadcast -s 'command scripting=true' -p 1 -n foo-1 foo
# ... (suite shuts down)
% cylc cat-log -e foo | tail -n 31
Traceback (most recent call last):
  File "/home/oliverh/cylc/cylc.git/lib/cylc/run.py", line 75, in main
    server.run()
  File "/home/oliverh/cylc/cylc.git/lib/cylc/scheduler.py", line 908, in run
    self.pool.wireless.expire( self.pool.get_min_point() )
  File "/home/oliverh/cylc/cylc.git/lib/cylc/broadcast.py", line 139, in expire
    get_point(point_string) < cutoff_point):
  File "/home/oliverh/cylc/cylc.git/lib/cylc/cycling/iso8601.py", line 116, in __cmp__
    return self._iso_point_cmp(self.value, other.value)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/cycling/iso8601.py", line 85, in _wrapper
    results = function(*args)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/cycling/iso8601.py", line 154, in _iso_point_cmp
    point = point_parse(point_string)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/cycling/iso8601.py", line 695, in point_parse
    return _point_parse(point_string).copy()
  File "/home/oliverh/cylc/cylc.git/lib/cylc/cycling/iso8601.py", line 85, in _wrapper
    results = function(*args)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/cycling/iso8601.py", line 715, in _point_parse
    point = SuiteSpecifics.point_parser.parse(point_string)  # Fail?
  File "/home/oliverh/cylc/cylc.git/lib/isodatetime/parsers.py", line 236, in parse
    date_info, time_info, parsed_expr = self.get_info(timepoint_string)
  File "/home/oliverh/cylc/cylc.git/lib/isodatetime/parsers.py", line 432, in get_info
    keys, date_info = self.get_date_info(date)
  File "/home/oliverh/cylc/cylc.git/lib/isodatetime/parsers.py", line 392, in get_date_info
    raise ISO8601SyntaxError("date", date_string)
ISO8601SyntaxError: Invalid ISO 8601 date representation: 1
ERROR CAUGHT: cleaning up before exit
2015-04-15T22:12:23+12 WARNING - some active tasks will be orphaned
THE ERROR WAS:
Invalid ISO 8601 date representation: 1
use --debug to turn on exception tracebacks)
```

**Comment by hjoliver** [comment]
Attempting to broadcast an illegal config item does not cause a problem, because validation catches that in the CLI.

Broadcasting to a namespace that is not defined in the suite is currently legal and doesn't cause any problems, but it won't have any effect.  We should probably make this illegal, or ignore it.

Broadcasting to any valid cycle point is legal, whether or not there are any live task proxies with that cycle point (but won't have any effect if there aren't any, obviously).  It's difficult to determine that there will never be a task with a given cycle point, so this should remain legal.

So I think the only way for broadcast to cause a fatal error in the suite daemon is an invalid cycle point, as above.
