### ISSUE TITLE
Better job submission failure errors?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1443]
Under the new(ish) job submission mechanism, choosing a job submission method that is not available on the task host results in an error that does not reveal the simple cause of the problem and is pretty much incomprehensible.  E.g. choosing loadleveler on a host without loadleveler installed I get this:

```
2015-05-04T01:17:31Z WARNING - Traceback (most recent call last):
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.4.0/bin/cylc-job-submit", line 58, in <module>
    main()
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.4.0/bin/cylc-job-submit", line 46, in main
    args[0], opts.remote_mode)
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.4.0/lib/cylc/batch_sys_manager.py", line 331, in job_submit
    stdin=proc_stdin_arg, stdout=PIPE, stderr=PIPE)
  File "/usr/lib64/python2.6/subprocess.py", line 639, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

2015-05-04T01:17:31Z ERROR - [foo.1] -submission failed
```

**Comment by matthewrmshin** [comment]
OK, it looks like we need to catch `OSError`, and set its `.filename` to the job submission command.
