### ISSUE TITLE
cylc broadcast during dumping can bring down a suite

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1539]
New problem seen today in our parallel suite.

It appears that while pickle dumping of the broadcast setting was occurring, a broadcast was actioned leading to an exception being thrown and the suite shutting down:

suite out:
```
Suite shutting down at 2015-07-17T10:15:03Z (ERROR: dictionary changed size during iteration)
```
suite log:
```
2015-07-17T10:15:02Z INFO - [nc_check.20150717T1015Z] -(current:submitted)> nc_check.20150717T1015Z started at 2015-07-17T10:15:02Z
2015-07-17T10:15:02Z INFO - Broadcast set:
+ [NC_HPC.20150717T1015Z] [remote]host=$(rose host-select xcf)
2015-07-17T10:15:03Z INFO - Suite shutting down at 2015-07-17T10:15:03Z (ERROR: dictionary changed size during iteration)
2015-07-17T10:15:03Z WARNING - some active tasks will be orphaned
```
suite err:
```
Traceback (most recent call last):
  File "/opt/cylc-6.4.0.u2/lib/cylc/run.py", line 75, in main
    server.run()
  File "/opt/cylc-6.4.0.u2/lib/cylc/scheduler.py", line 927, in run
    self.state_dumper.dump()
  File "/opt/cylc-6.4.0.u2/lib/cylc/suite_state_dumping.py", line 90, in dump
    wireless.dump(handle)
  File "/opt/cylc-6.4.0.u2/lib/cylc/broadcast.py", line 225, in dump
    pickle.dump(self.settings, file_)
RuntimeError: dictionary changed size during iteration
```

@benfitzpatrick found the following relevant posting via a quick google search:

http://bytes.com/topic/python/answers/467108-runtimeerror-dictionary-changed-size-during-iteration-good-atomiccopy-operations

which suggests that ultimately the problem is down to threaded access to the dictionary being dumped.

**Comment by arjclark** [comment]
I have noted that chunks of this code have been relocated since 6.4.0 so may be even harder to reproduce (am yet to be able to do so myself)
