### ISSUE TITLE
Starting a fresh install gives some error messages

### ISSUE THREAD

**Issue by m214089** [cylc/cylc#1590]
Hi,
I installed 6.6.1 and started the GUI and got those error messages.
As far as I understand it is not serious, but disturbing new users.
Cheerio,
Luis

```
m214089@mlogin100% ./cylc gui
Traceback (most recent call last):
  File "/mnt/lustre01/sw/rhel6-x64/cylc/cylc-6.6.1/lib/cylc/gui/app_gcylc.py", line 3229, in popup_filter_dialog
    self.check_task_filter_buttons()
  File "/mnt/lustre01/sw/rhel6-x64/cylc/cylc-6.6.1/lib/cylc/gui/app_gcylc.py", line 2934, in check_task_filter_buttons
    self.updater.filter_states_excl = task_states
AttributeError: 'NoneType' object has no attribute 'filter_states_excl'
Traceback (most recent call last):
  File "/mnt/lustre01/sw/rhel6-x64/cylc/cylc-6.6.1/lib/cylc/gui/app_gcylc.py", line 2934, in check_task_filter_buttons
    self.updater.filter_states_excl = task_states
AttributeError: 'NoneType' object has no attribute 'filter_states_excl'
Traceback (most recent call last):
  File "/mnt/lustre01/sw/rhel6-x64/cylc/cylc-6.6.1/lib/cylc/gui/app_gcylc.py", line 2952, in reset_filter_box
    self.check_task_filter_buttons()
  File "/mnt/lustre01/sw/rhel6-x64/cylc/cylc-6.6.1/lib/cylc/gui/app_gcylc.py", line 2934, in check_task_filter_buttons
    self.updater.filter_states_excl = task_states
AttributeError: 'NoneType' object has no attribute 'filter_states_excl'

```

**Comment by hjoliver** [comment]
Hi Luis, I can't seem to reproduce this ... but I'll take a look at the code tomorrow (if @matthewrmshin doesn't beat me to it...)

**Comment by hjoliver** [comment]
@m214089 - sorry, just got back to this.  According to my tests and examination of the code, this should not happen immediately on start-up as you've suggested, but I can reproduce the bug if I click on the state filtering icon in the task bar before any suite is connected - is this what you did?

**Comment by hjoliver** [comment]
Bug confirmed on current master branch.
