### ISSUE TITLE
loadleveler job poll broken at 6.7.0

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1649]
```
Processing 1 queued command(s)
  + poll_tasks
2015-10-22T12:09:59+13 ERROR - 2015-10-22T12:09:59+13 [jobs-poll cmd] cylc jobs-poll --host=fitzroy -- '$HOME/cylc-run/foo/log/job' 1/foo/01
2015-10-22T12:09:59+13 [jobs-poll ret_code] 1
2015-10-22T12:09:59+13 [jobs-poll err]

Traceback (most recent call last):
  File "/home/oliverh/cylc/cylc-6.7.1/bin/cylc-jobs-poll", line 43, in <module>
    main()
  File "/home/oliverh/cylc/cylc-6.7.1/bin/cylc-jobs-poll", line 37, in main
    BATCH_SYS_MANAGER.jobs_poll(args[0], args[1:])
  File "/gpfs_hpcf/filesets/hpcf/home/oliverh/cylc/cylc-6.7.1/lib/cylc/batch_sys_manager.py", line 308, in jobs_poll
    job_log_root, batch_sys_name, my_ctx_list)
  File "/gpfs_hpcf/filesets/hpcf/home/oliverh/cylc/cylc-6.7.1/lib/cylc/batch_sys_manager.py", line 616, in _jobs_poll_batch_sys
    head = line.split(None, 1)[0]
IndexError: list index out of range
ERROR: remote command terminated by signal 1


Traceback (most recent call last):
  File "/home/oliverh/cylc/cylc.git/lib/cylc/run.py", line 82, in main
    server.run()
  File "/home/oliverh/cylc/cylc.git/lib/cylc/scheduler.py", line 973, in run
    proc_pool.handle_results_async()
  File "/home/oliverh/cylc/cylc.git/lib/cylc/mp_pool.py", line 192, in handle_results_async
    callback(value)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/task_pool.py", line 781, in poll_task_jobs_callback
    lambda itask, line: itask.job_poll_message_callback(line),
  File "/home/oliverh/cylc/cylc.git/lib/cylc/task_pool.py", line 864, in _manip_task_jobs_callback
    callback(itask, "|".join([ctx.timestamp, job_log_dir, "1"]))
  File "/home/oliverh/cylc/cylc.git/lib/cylc/task_pool.py", line 781, in <lambda>
    lambda itask, line: itask.job_poll_message_callback(line),
  File "/home/oliverh/cylc/cylc.git/lib/cylc/task_proxy.py", line 792, in job_poll_message_callback
    priority, message = line.split("|")[3:5]
ValueError: need more than 0 values to unpack
ERROR CAUGHT: cleaning up before exit
Suite shutting down at 2015-10-22T12:09:59+13 (ERROR: need more than 0 values to unpack)
2015-10-22T12:09:59+13 WARNING - some active tasks will be orphaned
DONE
THE ERROR WAS:
need more than 0 values to unpack
use --debug to turn on exception tracebacks)
```

Two problems?: 1) polling of loadleveler jobs appears to be broken; 2) a failed remote job-poll command should not bring down the cylc daemon.

**Comment by hjoliver** [comment]
The polling tests all pass - so we need to have specific polling tests for each supported batch system.

**Comment by hjoliver** [comment]
The first error appears to be caused by a blank line in `llq` output.

**Comment by matthewrmshin** [comment]
(This is surprising, giving that this functionality was well tested in my toy suites while we still had loadleveler. I'll take a quick look to see what is going on.)
