### ISSUE TITLE
Back-compat with old cylc clients broken at 6.7.0

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1657]
https://github.com/cylc/cylc/pull/1612 stopped the logging of old-client denials, but unintentionally it also denies cylc-6.5.0 and older clients from connecting when they have the suite passphrase.  (I guess I should have done a more careful review of this change :grimacing:!):

```
$ cylc run --hold --no-detach foo &
...
$ CYLC_VERSION=6.5.0 cylc scan

# from the daemon:
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/oliverh/.local/lib/python2.7/site-packages/Pyro/protocol.py", line 1126, in connectionHandler
    if self.getAdapter().handleConnection(conn, self):
  File "/home/oliverh/.local/lib/python2.7/site-packages/Pyro/protocol.py", line 840, in handleConnection
    (ok,reasonCode) = tcpserver.newConnValidator.acceptIdentification(tcpserver,conn,token,challenge)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/network/connection_validator.py", line 97, in acceptIdentification
    connection.user = user
UnboundLocalError: local variable 'user' referenced before assignment
...
```

**Comment by hjoliver** [comment]
Duplicate of #1635.
