### ISSUE TITLE
Graphing day of week results in cylc ISO 8601 date syntax error

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1846]
Broken syntax, from the documentation I should be able to do this:
```
        # Repeat 5 times, every month starting on Monday following the 
        # initial cycle point 
        [[[ R5/W-1/P1M ]]] 
            graph = "monthly_spam => monthly_eggs" 
```
I get the following error:
```
[FAIL] "'W-1': not a valid cylc-shorthand or full ISO 8601 date representation"
```

**Comment by arjclark** [comment]
@benfitzpatrick - can you confirm that the above graphing should work? Am struggling to find a release where it did (doesn't validate for me for 6.0.0 which suggests functionality not implemented?).

**Comment by benfitzpatrick** [comment]
I think it should work.

**Comment by arjclark** [comment]
Traceback from running suite (not validating):
```
Traceback (most recent call last):
  File "/net/home/h06/aclark/cylc.git/lib/cylc/scheduler.py", line 230, in start
    self.configure()
  File "/net/home/h06/aclark/cylc.git/lib/cylc/scheduler.py", line 339, in configure
    self.configure_suite()
  File "/net/home/h06/aclark/cylc.git/lib/cylc/scheduler.py", line 1168, in configure_suite
    self.load_suiterc(reconfigure)
  File "/net/home/h06/aclark/cylc.git/lib/cylc/scheduler.py", line 1135, in load_suiterc
    mem_log_func=self.log_memory
  File "/net/home/h06/aclark/cylc.git/lib/cylc/config.py", line 149, in get_inst
    vis_start_string, vis_stop_string, mem_log_func)
  File "/net/home/h06/aclark/cylc.git/lib/cylc/config.py", line 552, in __init__
    self.load_graph()
  File "/net/home/h06/aclark/cylc.git/lib/cylc/config.py", line 2078, in load_graph
    tasks_to_prune=tasks_to_prune
  File "/net/home/h06/aclark/cylc.git/lib/cylc/config.py", line 2172, in parse_graph
    self.cfg['scheduling']['final cycle point']
  File "/net/home/h06/aclark/cylc.git/lib/cylc/cycling/loader.py", line 99, in get_sequence
    return get_sequence_cls(cycling_type=cycling_type)(*args, **kwargs)
  File "/net/home/h06/aclark/cylc.git/lib/cylc/cycling/iso8601.py", line 346, in __init__
    self.recurrence = self.abbrev_util.parse_recurrence(recurrence_syntax)
  File "/net/home/h06/aclark/cylc.git/lib/cylc/time_parser.py", line 206, in parse_recurrence
    allow_truncated=True
  File "/net/home/h06/aclark/cylc.git/lib/cylc/time_parser.py", line 372, in _get_point_from_expression
    "ISO 8601 date representation")
CylcTimeSyntaxError: "'W-1': not a valid cylc-shorthand or full ISO 8601 date representation"
```
