### ISSUE TITLE
Reload after removing a task and its runtime definition fails since cylc-10.0.0

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1867]
The current reload  remove-task test removes a task from the graph, but not its [runtime] definition.

Test case:
```
[scheduling]
    [[dependencies]]
          graph = foo => bar
[runtime]   
    [[foo]]
    [[bar]]
```

Start suite with `--hold`; remove `bar` from graph and runtime; reload:
```
Processing 1 queued command(s)
  + reload_suite
Traceback (most recent call last):
  File "/home/oliverh/cylc/cylc.git/lib/cylc/scheduler.py", line 236, in start
    self.run()
  File "/home/oliverh/cylc/cylc.git/lib/cylc/scheduler.py", line 1591, in run
    self.update_state_summary()
  File "/home/oliverh/cylc/cylc.git/lib/cylc/scheduler.py", line 1669, in update_state_summary
    self.config.ns_defn_order, self.pool.do_reload)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/network/suite_state.py", line 146, in update
    for parent in ancestors_dict[key]:
KeyError: 'bar'
```

Works fine back at 6.9.1:
```
Processing 1 queued command(s)
  + reload_suite
RELOADING the suite definition
2016-05-26T15:54:00+12 WARNING - orphaned task will not continue: bar.1
```

**Comment by hjoliver** [comment]
Broken by #1811

**Comment by arjclark** [comment]
Testing on HEAD seems to suggest that removing `bar` from graphing *only* is fine but removing the runtime as well causes a problem.

**Comment by hjoliver** [comment]
> removing bar from graphing only is fine but removing the runtime as well causes a problem.

Yes, hence the "and" in the issue title :wink:

**Comment by arjclark** [comment]
Yeah, just wanted to make sure that it wasn't throwing problems otherwise...
