### ISSUE TITLE
gcylc: traceback when attempting to view job files

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2037]
The following traceback can be obtained by trying to open job files through the gui after a restart.

```
Traceback (most recent call last):
  File "/net/home/h06/osanders/cylc.git/lib/cylc/gui/app_gcylc.py", line 1220, in view_task_info
    self._popup_logview(task_id, task_state_summary, choice)
  File "/net/home/h06/osanders/cylc.git/lib/cylc/gui/app_gcylc.py", line 2243, in _popup_logview
    try:
TypeError: argument of type 'NoneType' is not iterable
```

Since 6.11.0

**Comment by matthewrmshin** [comment]
Is this the same bug as #2012? Or something different?

**Comment by oliver-sanders** [comment]
Duplicate of #2012.
