### ISSUE TITLE
OSError can't fork, in gscan

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2039]
See also #2006 #2009

Heavy user (same as in #2009) got an unresponsive non-updating gscan, terminal showed this:

```
 Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.11.1/lib/cylc/gui/gscan.py", line 884, in run
    prev_hosts_suites=self.prev_hosts_suites
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.11.1/lib/cylc/gui/gscan.py", line 1179, in update_hosts_suites_info
    hosts_suites_info = get_hosts_suites_info(hosts, owner=owner)
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.11.1/lib/cylc/gui/gscan.py", line 57, in get_hosts_suites_info
    hosts=hosts, pyro_timeout=timeout):
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.11.1/lib/cylc/network/port_scan.py", line 160, in scan_all
    proc_pool = Pool(proc_pool_size)
  File "/usr/lib64/python2.6/multiprocessing/__init__.py", line 227, in Pool
    return Pool(processes, initializer, initargs)
  File "/usr/lib64/python2.6/multiprocessing/pool.py", line 104, in __init__
    w.start()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 104, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 94, in __init__
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable
```

This link suggests that multiprocessing.Pool does not clean up after such an error, making it impossible to recover from this in the same Python interpreter instance: http://bugs.python.org/issue19675

But I guess we could catch the exception, pop up a warning dialog, and then shut down gracefully (or supply our own Pool extension class to fix it, as in the linked bugs.python.org issue)

**Comment by matthewrmshin** [comment]
Note: since #2060, we no longer use `multiprocess.Pool` in `cylc.network.https.port_scan`. We now manage our own process pool, so we should be able to handle `OSError` on forking.
