### ISSUE TITLE
gcylc bug for newly registered suites

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2082]
Something to fix for cylc-7: on current master, if I start gcylc on a newly registered suite with no existing run directory, the updater thread dies and the gcylc instance will never connect to the suite (if it gets started):

```
$ gcylc nwp/foo
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vagrant/cylc/lib/cylc/gui/updater.py", line 523, in run
    if self.update():
  File "/home/vagrant/cylc/lib/cylc/gui/updater.py", line 393, in update
    self.reconnect()
  File "/home/vagrant/cylc/lib/cylc/gui/updater.py", line 216, in reconnect
    self.stop_summary[0]["last_updated"])
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by matthewrmshin** [comment]
(Sorry, looks like I have missed `TypeError` in the list of exceptions to catch.)
