### ISSUE TITLE
Remote suite access bug.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2340]
Access to a suite running under another user account fails with a traceback if `--host` is not specified (should default to localhost):
```
$  cylc scan -a
foo vagrant@localhost:43069

$ cylc ping --debug --user=vagrant foo
Traceback (most recent call last):
  File "/home/vagrant/cylc.git/bin/cylc-ping", line 81, in <module>
    main()
  File "/home/vagrant/cylc.git/bin/cylc-ping", line 64, in main
    pclient.get_info('ping_suite')  # (no need to check the result)
  File "/home/vagrant/cylc.git/lib/cylc/network/https/suite_info_client.py", line 39, in get_info
    return self.call_server_func(COMMS_INFO_OBJ_NAME, *command, **arg_dict)
  File "/home/vagrant/cylc.git/lib/cylc/network/https/base_client.py", line 97, in call_server_func
    self._load_contact_info()
  File "/home/vagrant/cylc.git/lib/cylc/network/https/base_client.py", line 345, in _load_contact_info
    self.suite, self.owner, self.host)
  File "/home/vagrant/cylc.git/lib/cylc/suite_srv_files_mgr.py", line 350, in load_contact_file
    self.FILE_BASE_CONTACT, reg, owner, host, content=True)
  File "/home/vagrant/cylc.git/lib/cylc/suite_srv_files_mgr.py", line 269, in get_auth_item
    value = self._load_remote_item(item, reg, owner, host)
  File "/home/vagrant/cylc.git/lib/cylc/suite_srv_files_mgr.py", line 611, in _load_remote_item
    command += ['-n', owner + '@' + host, script]
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by matthewrmshin** [comment]
This is another aspect of the original description of #526 - which says we should try looking for the ~port~ contact file in the local file system before using non-interactive SSH. (Obviously, the `ssl.cert` issue highlighted in #2341 makes this a bit more complicated.)
