### ISSUE TITLE
"cylc graph" right-click group/group broken since 7.4.0

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2351]
Something's gone wrong here.  Test suite:
```
[scheduling]
    [[dependencies]]
         graph = foo => FAM:succeed-all => bar
[runtime]
    [[FAM]]
    [[BAM]]
        inherit = FAM
    [[wam]]
        inherit = FAM
    [[x, y]]
        inherit = BAM
```

This graphs correctly at 7.4.0, and right-click collapse expand works properly.  On current master I get this, which is wrong, and right-click collapse/expand does nothing:

![foo-1](https://user-images.githubusercontent.com/2362137/27943346-a3b017c2-6321-11e7-92e7-b2103d9f9b71.png)

**Comment by hjoliver** [comment]
Additionally, right-click -> Group dumps a traceback:
```
Traceback (most recent call last):
  File "/home/vagrant/cylc.git/bin/cylc-graph", line 144, in grouping
    window.get_graph(group_nodes=[name])
  File "/home/vagrant/cylc.git/lib/cylc/cylc_xdot.py", line 399, in get_graph
    subgraphs_on=self.subgraphs_on)
  File "/home/vagrant/cylc.git/lib/cylc/graphing.py", line 378, in get_graph
    group_all, ungroup_all)
  File "/home/vagrant/cylc.git/lib/cylc/config.py", line 1675, in get_graph_raw
    parent = hierarchy[node][1]
KeyError: 'base:BAM'
```
