### ISSUE TITLE
problem with remote job suites (recent commit)

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2369]
```
[scheduling]
   [[dependencies]]
       graph = foo
[runtime]
   [[foo]]
       [[[remote]]]
            host = localhost
            owner = hobo
```

Daemon aborts with;

```
ERROR - Traceback (most recent call last):
	  File "/home/vagrant/cylc.git/lib/cylc/task_job_mgr.py", line 813, in _prep_submit_task_job
	    job_conf = self._prep_submit_task_job_impl(suite, itask)
	  File "/home/vagrant/cylc.git/lib/cylc/task_job_mgr.py", line 915, in _prep_submit_task_job_impl
	    self.init_host(suite, itask.task_host, itask.task_owner)
	  File "/home/vagrant/cylc.git/lib/cylc/task_job_mgr.py", line 213, in init_host
	    proc = Popen(cmd, stdout=PIPE, stderr=PIPE)
	  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
	    errread, errwrite)
	  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
	    raise child_exception
	OSError: [Errno 13] Permission denied

```

**Comment by hjoliver** [comment]
```
$ git bisect bad
4df408e8d5576a197e6383450f6865dd7752eefb is the first bad commit
...
Date:   Wed Jul 19 12:55:34 2017 +0100
Logic for dealing with no SSL in task_job_mgr
...
```

**Comment by hjoliver** [comment]
(the commit looks innocent enough!)

**Comment by matthewrmshin** [comment]
Looks like call to `self.suite_srv_files_mgr.get_auth_item` should have `owner` and `host` in the argument list.

**Comment by dvalters** [comment]
It should still abort though if the 'owner@host' is invalid, right? (Just checking I'm not missing something obvious here..) 
(#2371 should fix this)
