### ISSUE TITLE
An unhandled Jinja2 error

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2550]
Suites with unpacking errors in their Jinja2 code do not get a user-friendly error message:

```
!Jinja2
{% set foo = [1, 2] %}
{% set a, b, c = foo %}
```

Result:
```
$ cylc validate suite.rc 
need more than 2 values to unpack

$ cylc validate --debug suite.rc

Traceback (most recent call last):
  File "/home/vagrant/cylc.git/bin/cylc-validate", line 123, in <module>
    main()
  File "/home/vagrant/cylc.git/bin/cylc-validate", line 83, in main
    mem_log_func=profiler.log_memory)
  File "/home/vagrant/cylc.git/lib/cylc/config.py", line 158, in __init__
    self.pcfg = RawSuiteConfig(fpath, output_fname, template_vars)
  File "/home/vagrant/cylc.git/lib/cylc/cfgspec/suite.py", line 567, in __init__
    self.loadcfg(fpath, "suite definition")
  File "/home/vagrant/cylc.git/lib/parsec/config.py", line 70, in loadcfg
    sparse = parse(rcfile, self.output_fname, self.tvars)
  File "/home/vagrant/cylc.git/lib/parsec/fileparse.py", line 313, in parse
    flines = read_and_proc(fpath, template_vars)
  File "/home/vagrant/cylc.git/lib/parsec/fileparse.py", line 268, in read_and_proc
    flines = jinja2process(flines, fdir, template_vars)
  File "/home/vagrant/cylc.git/lib/parsec/jinja2support.py", line 94, in jinja2process
    for line in str(template.render(template_vars)).splitlines():
  File "/home/vagrant/cylc.git/lib/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vagrant/cylc.git/lib/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 2, in top-level template code
ValueError: need more than 2 values to unpack
```

Can we catch this and point to the bad line?

**Comment by matthewrmshin** [comment]
I'll do this with #2497.
