### ISSUE TITLE
graph_parser.py test_bad_node_syntax bug and bug in node order validation

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc#2645]
I noticed that with the `test_bad_node_syntax` test, if you check what the exceptions thrown are not what are expected. They are because parameters are not defined, not because of the order of the graph node.

For example, if I do the first one without the assertRaises call, the message is:
```python
Traceback (most recent call last):
  File "lib/cylc/graph_parser.py", line 681, in test_bad_node_syntax
    gp.parse_graph("foo[-P1Y]<m,n> => bar")
  File "lib/cylc/graph_parser.py", line 252, in parse_graph
    raise GraphParseError(str(exc))
GraphParseError: ERROR, parameter m is not defined in <m,n>: foo[-P1Y]<m,n> => bar
```

If you define the parameters, then it will not thrown anything.

There is a bug in the validation of node syntax that should be resolved.

**Comment by ColemanTom** [comment]
This was resolved in https://github.com/cylc/cylc/pull/2646
