### ISSUE TITLE
Bug in task_action_timers load on restart?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2702]
On current master, after restarting a simple test suite:
```
Traceback (most recent call last):
  File "/home/vagrant/cylc.git/lib/cylc/task_pool.py", line 430, in load_db_task_action_timers
    ctx_key = json.loads(str(ctx_key_raw))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by matthewrmshin** [comment]
What was the Cylc version used to run the original suite before running the restart? (Need to figure out how best to reproduce.)

See also #2678.

**Comment by hjoliver** [comment]
Both on current master.

**Comment by hjoliver** [comment]
line 430 in `task_pool.py` is:
```
     ctx_key = json.loads(str(ctx_key_raw))  
```

When the error occurs, the value of `ctx_key_raw` is `"poll_timer"`.
I guess a plain string is not valid json?

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> json.loads("poll_timer")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by hjoliver** [comment]
For the record, my simple test suite (but I suspect any suite will do):
```
[scheduling]
    initial cycle point = 1
    cycling mode = integer
    [[dependencies]]
        [[[P1]]]
          graph = foo => bar
[runtime]
    [[foo]]
        script = sleep 10
```

**Comment by matthewrmshin** [comment]
Bug repeated. On the case to fix it now.

**Comment by matthewrmshin** [comment]
(We don't notice this because it prints out a skip message + the traceback, so restart does not fail.)

**Comment by matthewrmshin** [comment]
(The bug looks nasty, but is also relatively harmless.)
