### ISSUE TITLE
gui tree view dt-mean column sort bug

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2791]
While using `cylc gui`, a user reported that he was getting this popup on his screen every 2 seconds.

```
gcylc has a problem.
 
Traceback (most recent call last):
  File "/opt/cylc-7.7.2/lib/cylc/gui/view_tree.py", line 249, in sort_column
    prop2 = self._get_interval_in_seconds(prop2)
  File "/opt/cylc-7.7.2/lib/cylc/gui/view_tree.py", line 260, in _get_interval_in_seconds
    interval = self.interval_parser.parse(val)
  File "/opt/cylc-7.7.2/lib/isodatetime/parsers.py", line 553, in parse
    if expression.startswith("-"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by oliver-sanders** [comment]
Any idea how to reproduce this one?

**Comment by matthewrmshin** [comment]
No. I am unable to reproduce.

**Comment by hjoliver** [comment]
(I couldn't reproduce this either).
