### ISSUE TITLE
Propagate host info when socket errors occur

### ISSUE THREAD

**Issue by kinow** [cylc/cylc#2875]
While testing the auto stop-restart PR #988, I had a few hiccups with my local environment, and realized that one exception I was getting wasn't very helpful.

```bash
root@a5442ac9d102:/opt/cylc# cylc run --debug stop-restart
2018-11-21T23:46:11Z DEBUG - Loading site/user global config files
2018-11-21T23:46:11Z DEBUG - Reading file /root/.cylc/global.rc
2018-11-21T23:46:11Z DEBUG - Loading site/user global config files
2018-11-21T23:46:11Z DEBUG - Reading file /root/.cylc/global.rc
Traceback (most recent call last):
  File "/opt/cylc/bin/cylc-run", line 25, in <module>
    main(is_restart=False)
  File "/opt/cylc/lib/cylc/scheduler_cli.py", line 105, in main
    host = HostAppointer().appoint_host()
  File "/opt/cylc/lib/cylc/host_appointer.py", line 78, in __init__
    global_config.get(['suite servers', 'condemned hosts'])]
  File "/opt/cylc/lib/cylc/hostuserutil.py", line 229, in get_fqdn_by_host
    return HostUtil.get_inst().get_fqdn_by_host(target)
  File "/opt/cylc/lib/cylc/hostuserutil.py", line 153, in get_fqdn_by_host
    return self._get_host_info(target)[0]
  File "/opt/cylc/lib/cylc/hostuserutil.py", line 121, in _get_host_info
    self._host_exs[target] = socket.gethostbyname_ex(target)
socket.gaierror: [Errno -2] Name or service not known
```

The error occurred due to a network issue, which my DNS setup is incomplete. After fixing the issue by adding an entry to my `/etc/hosts`, the commands works fine.

But a user with similar environment could raise an issue thinking there is something wrong with Cylc.

We could instead raise a `CylcError` with more information.

```diff
diff --git a/lib/cylc/hostuserutil.py b/lib/cylc/hostuserutil.py
index 94eed87f9..6a8bba125 100644
--- a/lib/cylc/hostuserutil.py
+++ b/lib/cylc/hostuserutil.py
@@ -51,6 +51,7 @@ import pwd
 import socket
 from time import time
 
+from cylc.exceptions import CylcError
 from cylc.cfgspec.glbl_cfg import glbl_cfg
 
 
@@ -118,7 +119,10 @@ class HostUtil(object):
         if target not in self._host_exs:
             if target is None:
                 target = socket.getfqdn()
-            self._host_exs[target] = socket.gethostbyname_ex(target)
+            try:
+                self._host_exs[target] = socket.gethostbyname_ex(target)
+            except socket.gaierror as ge:
+                raise CylcError("Failed to retrieve host info for " + target)
         return self._host_exs[target]
 
     @staticmethod
```

Which results in:

```bash
root@a5442ac9d102:/opt/cylc# cylc run --debug stop-restart
2018-11-21T23:49:16Z DEBUG - Loading site/user global config files
2018-11-21T23:49:16Z DEBUG - Reading file /root/.cylc/global.rc
2018-11-21T23:49:16Z DEBUG - Loading site/user global config files
2018-11-21T23:49:16Z DEBUG - Reading file /root/.cylc/global.rc
Traceback (most recent call last):
  File "/opt/cylc/bin/cylc-run", line 25, in <module>
    main(is_restart=False)
  File "/opt/cylc/lib/cylc/scheduler_cli.py", line 105, in main
    host = HostAppointer().appoint_host()
  File "/opt/cylc/lib/cylc/host_appointer.py", line 78, in __init__
    global_config.get(['suite servers', 'condemned hosts'])]
  File "/opt/cylc/lib/cylc/hostuserutil.py", line 233, in get_fqdn_by_host
    return HostUtil.get_inst().get_fqdn_by_host(target)
  File "/opt/cylc/lib/cylc/hostuserutil.py", line 155, in get_fqdn_by_host
    if not self.is_remote_host(target):
  File "/opt/cylc/lib/cylc/hostuserutil.py", line 187, in is_remote_host
    host_info = self._get_host_info(name)
  File "/opt/cylc/lib/cylc/hostuserutil.py", line 125, in _get_host_info
    raise CylcError("Failed to retrieve host info for " + target)
cylc.exceptions.CylcError: 'Failed to retrieve host info for ea21caacc34a'
```

Giving us and the user more information to which host failed. Then s/he can go and check with IT/network to see why it is not resolving to that host correctly.

**Comment by kinow** [comment]
Even better if we can propagate the original exception too. But alas that's available only with Python 3.

```python
raise CylcError("Failed to retrieve host info for " + target) from e
```

That way we can preserve the stack trace with traceback/logging.

**Comment by matthewrmshin** [comment]
`socket.gaierror` is a sub-class of `IOError`, which has an attribute `filename` we can make use of.

E.g.:

```python
target = 'nosuchhost.nosuchdomain.org'
try:
    socket.gethostbyname_ex(target)
except socket.gaierror as exc:
    if exc.filename is None:
        exc.filename = target
    raise
```

Should result in this:

```
Traceback (most recent call last):
...
socket.gaierror: [Errno -2] Name or service not known: 'nosuchhost.nosuchdomain.org'
```
