### ISSUE TITLE
cylc gui: keyboard interrupt handling broken

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2898]
To repeat, launch `cylc gui` on a running suite in a terminal. Type Ctrl-C in the terminal to send SIGINT and see the GUI hang. I guess some threads are not being shutdown correctly?

2nd problem: Launch `cylc gscan` in a terminal. Launch `cylc gui` on a running suite from `cylc gscan`. Type Ctrl-C in the termainl to send SIGINT to `cylc gscan` - and watch the `cylc gui` GUI hangs in the same way. Do we want to launch `cylc gui` processes in their own process group so they are properly detached from `cylc gscan`?

Reported by @steoxley.

**Comment by kinow** [comment]
I thought that was the normal behaviour? At least the 1st one. Noticed some time ago while playing with `cylc gui`... probably weeks ago I think. Here's the logs from reproducing locally

```bash
2018-11-30T10:32:42Z INFO - [prep.20130808T0000Z] -health check settings: execution timeout=None
^C2018-11-30T10:32:43Z INFO - Suite shutting down
2018-11-30T10:32:43Z WARNING - prep.20130808T0000Z: orphaned task (running)
2018-11-30T10:32:50Z INFO - DONE
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc/bin/cylc-gui", line 120, in <module>
    main()
  File "/home/kinow/Development/python/workspace/cylc/bin/cylc-gui", line 115, in main
    gtk.main()
KeyboardInterrupt
Killed
```

And a naive fix which worked for me but haven't properly tested.

```diff
diff --git a/bin/cylc-gui b/bin/cylc-gui
index e4f58a8bf..18a5ff6bd 100755
--- a/bin/cylc-gui
+++ b/bin/cylc-gui
@@ -107,12 +107,15 @@ def main():
             print >> sys.stderr, ('USER_AT_HOST must take the form '
                                   '"user@host:port"')
             sys.exit(1)
-    ControlApp(
+    app = ControlApp(
         suite, options.owner, options.host,
         options.port, options.comms_timeout,
         load_template_vars(options.templatevars, options.templatevars_file),
         options.restricted)
-    gtk.main()
+    try:
+        gtk.main()
+    except KeyboardInterrupt:
+        app.quit()
 
 
 if __name__ == "__main__":
```

Which gives:

```bash
cylc gui five
cylc run   --no-detach five 
            ._.                                                       
            | |              The Cylc Suite Engine [7.8.0-dirty]      
._____._. ._| |_____.           Copyright (C) 2008-2018 NIWA          
| .___| | | | | .___|   & British Crown (Met Office) & Contributors.  
| !___| !_! | | !___.  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
!_____!___. |_!_____!  This program comes with ABSOLUTELY NO WARRANTY;
      .___! |          see `cylc warranty`.  It is free software, you 
      !_____!           are welcome to redistribute it under certain  
2018-11-30T10:45:16Z INFO - Suite server: url=https://ranma:43081/ pid=8743
2018-11-30T10:45:16Z INFO - Run: (re)start=0 log=1
2018-11-30T10:45:16Z INFO - Cylc version: 7.8.0-dirty
2018-11-30T10:45:16Z INFO - Run mode: live
2018-11-30T10:45:16Z INFO - Initial point: 20130808T0000Z
2018-11-30T10:45:16Z INFO - Final point: 20130812T0000Z
2018-11-30T10:45:16Z INFO - Cold Start 20130808T0000Z
2018-11-30T10:45:16Z INFO - [prep.20130808T0000Z] -submit-num=1, owner@host=ranma
2018-11-30T10:45:17Z INFO - [prep.20130808T0000Z] -(current:ready) submitted at 2018-11-30T10:45:16Z
2018-11-30T10:45:17Z INFO - [prep.20130808T0000Z] -health check settings: submission timeout=None
2018-11-30T10:45:17Z INFO - [prep.20130808T0000Z] -(current:submitted)> started at 2018-11-30T10:45:16Z
2018-11-30T10:45:17Z INFO - [prep.20130808T0000Z] -health check settings: execution timeout=None
2018-11-30T10:45:17Z INFO - [client-command] get_latest_state kinow@ranma:cylc-gui fe92cdff-dc35-4f58-a8d9-c91db94add31
2018-11-30T10:45:18Z INFO - [prep.20130808T0000Z] -(current:running)> succeeded at 2018-11-30T10:45:17Z
2018-11-30T10:45:19Z INFO - [foo.20130808T0000Z] -submit-num=1, owner@host=ranma
^Ccalled outside of a mainloop
2018-11-30T10:45:19Z INFO - Suite shutting down
```

(started with no-detach on gui)

**Comment by matthewrmshin** [comment]
An unresponsive hanging GUI is definitely not normal behaviour. I think your fix should work.

**Comment by kinow** [comment]
We are now working [on the new Web GUI](https://github.com/cylc/cylc/issues/1873), which will replace the previous Desktop PyGTK GUI in our next major release of Cylc 8.

This issue is being closed for not being applicable to this new Web GUI.

**Comment by hjoliver** [comment]
Actually @kinow - can we still apply your "naive fix" above, to make the cylc-7 GUI a little better until cylc-8 is out?

**Comment by kinow** [comment]
Sure thing @hjoliver , can't see why not. For one second I thought the only complication would be that someone would have to cherry-pick or prepare a commit to python3 branch. Then realized actually this file is going to be deleted. Pull request on the way.
